//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedule
    {
        public int IdSchedule { get; set; }
        public int IdEmployee { get; set; }
        public System.DateTime WorkDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
